### ISSUE TITLE
change ADC readout port with bitstream

### ISSUE THREAD

**Issue by lisafan122** [openquantumhardware/qick#213] opened 2023-12-31 00:17 UTC
Hi,

I have a by default ZCU111 with ADC224 ports to read. But I want to use 226 or 227. I have bitstream files built from the previous commit in this repo. But when I check the ADC port using QickSoc(), it still gives me the default setup. 

I perhaps forgot to change something aside from using that commit repo. Can you please suggest some?

Best,
Jaz

**Comment by meeg** [comment] 2023-12-31 22:06
I don't think I understand. What commit are you talking about? The ZCU111 projects in this repo have always placed two readouts on ADC224.

**Comment by lucyfan7266** [comment] 2023-12-31 22:13
Hi @meeg ,thank you for reply. I have used Vivado on proj_111.tcl (with bd_2022_2.tcl inside), generate a new bitstream .bit, and .hwh file and I want to load this bitstream into the ZCU111 board, so that my ADC ports are switched to 226. What is the right way to load the new bitstream into the ZCU111 board? I am using qick and QickSoc() will output the port descriptions. I hope to change the port according to my new bitstream. thanks

**Comment by meeg** [comment] 2024-01-02 17:39
Duplicate of #216

**Closed** 2024-03-13 18:25 UTC
